# read the times in the .txt files generated by running pbs files
# each .txt file contains ten times in seconds for fixed values to n, p, and diff
import numpy
import pickle
from decimal import Decimal

timeFile = open("timeArray.txt","wb")

ns = [100, 500, 1000, 5000, 10000]
ps = [1, 4, 9, 16, 25, 36, 49, 64]
diff = [0.1, 0.5, 0.9]

times = numpy.zeros((5,8,3))
for i,n in enumerate(ns):
	for j,p in enumerate(ps):
		for k,d in enumerate(diff):
				instance = str(n)+"A"+str(p)+"A"+str(int(10*d))+"A"
				fileName = instance +".txt"
				f = open(fileName,"r")
				average = 0
				for l in range(10):
					average += float(f.readline().strip())
				average /= 10
				times[i,j,k] = average
				print(average)
				f.close()
pickle.dump(times,timeFile)
timeFile.close()



